server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: webapp/view/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/test?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
